spotted_fb_login:
    resource: "@SpottedFBLoginBundle/Resources/config/routing.yml"
    prefix:   /

spotted_home:
    resource: "@SpottedHomeBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@SpottedFBLoginBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@SpottedFBLoginBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@SpottedFBLoginBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@SpottedFBLoginBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@SpottedFBLoginBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

