services:
       my.facebook.user:
           #FacebookUserProvider
           class: Spotted\HomeBundle\Security\User\Provider\FacebookProvider 
           arguments:
               facebook: "@fos_facebook.api"
               userManager: "@fos_user.user_manager"
               validator: "@validator"
               container: "@service_container"

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chainprovider:
            chain:
                providers: [fos_FBLoginBundle, fos_facebook_provider]
        fos_facebook_provider:
            id: fos_facebook.user.login
        fos_FBLoginBundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/ZHAW-Spotted/"
                server_url: "http://localhost/facebookApp/"
                login_path: /user/login
                check_path: /facebook/login_check
                provider: fos_facebook_provider
                default_target_path: /
            form_login:
                provider: fos_FBLoginBundle
                csrf_provider: form.csrf_provider
                default_target_path: /home
            logout:
                path:   /logout
                target: /login
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        - { path: ^/facebook/,           role: [ROLE_FACEBOOK] }
        - { path: ^/home, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
