security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_facebook_provider:
            id: my.facebook.user
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/ZHAW-Spotted/"
                server_url: "http://localhost/spotted/"
                login_path: /login
                check_path: /login_facebook_check
                provider: fos_facebook_provider
                default_target_path: spotted_secured_homepage
                always_use_default_target_path: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: spotted_secured_homepage
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
                delete_cookies:
                        fbs_542881899137127: { path: "/", domain: "localhost" }
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     spotted_secured_homepage
                domain:   ~ # Defaults to the current domain from $_SERVER
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY, ROLE_USER] } # This is the route secured with fos_facebook
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/, role: ROLE_ADMIN }

