spotted_open_landingpage:
    pattern:  /
    defaults: { _controller: SpottedHomeBundle:Default:landing }

spotted_secured_homepage:
    pattern:  /secured/home/{confirmed}
    defaults: { _controller: SpottedHomeBundle:Default:index, confirmed: null }

spotted_secured_notifications:
    pattern:  /secured/notifications
    defaults: { _controller: SpottedHomeBundle:Default:notifications }

spotted_secured_submission:
    pattern:  /secured/submission
    defaults: { _controller: SpottedHomeBundle:Default:create }

spotted_secured_listlocations:
    pattern: /secured/listlocations
    defaults: { _controller: SpottedHomeBundle:Default:listlocations }
    options:
        expose: true

spotted_secured_filters:
    pattern: /secured/filters
    defaults: { _controller: SpottedHomeBundle:Post:filter }
    options:
        expose: true
spotted_secured_watchlist:
    pattern: /secured/watchlist
    defaults: { _controller: SpottedHomeBundle:Watchlist:index }
    options:
        expose: true
spotted_secured_add_watchlist:
    pattern: /secured/add_watchlist/{postid}
    defaults: { _controller: SpottedHomeBundle:Watchlist:add }
    options:
        expose: true
spotted_secured_del_watchlist:
    pattern: /secured/del_watchlist/{postid}
    defaults: { _controller: SpottedHomeBundle:Watchlist:del }
    options:
        expose: true
spotted_secured_add_comment:
    pattern: /secured/add_comment/{postid}
    defaults: { _controller: SpottedHomeBundle:Comment:create }
    options:
        expose: true
spotted_secured_show_comment:
    pattern: /secured/show_comment/{postid}
    defaults: { _controller: SpottedHomeBundle:Comment:show }
    options:
        expose: true
spotted_secured_show_post:
    pattern: /secured/post/{postid}
    defaults: { _controller: SpottedHomeBundle:Post:show }
    options:
        expose: true
spotted_secured_more_comments:
    pattern: /secured/more_comments/{postid}/{commentid}
    defaults: { _controller: SpottedHomeBundle:Comment:more }
    options:
        expose: true
spotted_home_single_comment:
    pattern:  /comment/{id}
    defaults: { _controller: SpottedHomeBundle:Default:comment }

spotted_secured_sendmail:
    pattern: /secured/sendmail/{postid}
    defaults: { _controller: SpottedHomeBundle:Default:contact }
    options:
        expose: true

spotted_secured_getposts:
    pattern: /secured/getposts/{watchlist}
    defaults: { _controller: SpottedHomeBundle:Default:getPosts, watchlist: null }
    options:
        expose: true

user_logout:
       pattern:   /logout