parameters:
#    spotted_fb_login.example.class: Spotted\FBLoginBundle\Example

services:
#    spotted_fb_login.example:
#        class: %spotted_fb_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
