Spotted\HomeBundle\Entity\Comments:
    type: entity
    table: Comments
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        text:
            type: text
            nullable: false
        date:
            type: datetime
            nullable: false
        rd:
            type: integer
            nullable: false
    manyToOne:
        post:
            targetEntity: Post
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Post_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
