Spotted\HomeBundle\Entity\Location:
    type: entity
    table: Location
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: Name
        ortId:
            type: integer
            unsigned: false
            nullable: true
            column: Ort_ID
    lifecycleCallbacks: {  }
