Spotted\HomeBundle\Entity\Notification:
    type: entity
    table: Notification
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: true
        read:
            type: boolean
            nullable: true
    manyToOne:
        comments:
            targetEntity: Comments
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Comments_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
