Spotted\HomeBundle\Entity\Post:
    type: entity
    table: Post
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        text:
            type: text
            nullable: false
        date:
            type: datetime
            nullable: false
        gender:
            type: string
            length: 45
            fixed: false
            nullable: false
    manyToOne:
        location:
            targetEntity: Location
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Location_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                User_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        tags:
            targetEntity: Tags
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Tags_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
