Spotted\HomeBundle\Entity\User:
    type: entity
    table: User
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
        vorname:
            type: string
            length: 45
            fixed: false
            nullable: true
        eMail:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: e-mail
        passwort:
            type: string
            length: 45
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
