Spotted\HomeBundle\Entity\Watchlist:
    type: entity
    table: Watchlist
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: watchlist
            joinColumns:
                User_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        post:
            targetEntity: Post
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Post_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
